name: Evaluate

on:
  pull_request_target:
  push:
    branches:
      - master

jobs:
  evaluator:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v2

      - name: Set up Python 3.7
        uses: actions/setup-python@v2
        with:
          python-version: '3.7'

      - name: Run Evaluation
        id: evaluation
        run: |
          RESULT=$(python3 evaluate.py)
          echo "${RESULT}"
          # hack for multiline output
          RESULT="${RESULT//'%'/'%25'}"
          RESULT="${RESULT//$'\n'/'%0A'}"
          RESULT="${RESULT//$'\r'/'%0D'}"
          echo "::set-output name=result::${RESULT}"

      - run: echo "${{ github.event_name }}"
      - run: env

      - name: Send Results as Comment
        if: ${{ github.event_name == 'pull_request_target' }}
        uses: unsplash/comment-on-pr@master
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        with:
          msg: "```\n${{ steps.evaluation.outputs.result }}\n```"
          check_for_duplicate_msg: true
