name: Evaluate

on:
  pull_request:
  push:
    branches:
      - master

jobs:
  evaluator:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v2

      - name: Set up Python 3.7
        uses: actions/setup-python@v2
        with:
          python-version: '3.7'

      - name: Run Evaluation
        id: evaluation
        run: |
          RESULT=$(python3 evaluate.py)
          echo "${RESULT}"
          echo "::set-output name=result::${RESULT}"

      - name: Send Results as Comment
        if: ${{ github.event_name == 'pull_request' }}
        uses: unsplash/comment-on-pr@master
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        with:
          msg: "${{ steps.evaluation.outputs.result }}"
          check_for_duplicate_msg: true
